New tests

diff --git a/.travis.d/init b/.travis.d/init
--- a/.travis.d/init
+++ b/.travis.d/init
@@ -1,49 +1,67 @@
 #!/bin/sh
-export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-mount -t tmpfs none "/tmp"
-mount -t tmpfs none "/var/run"
-mount -t hostfs -o "$LOGDIR" none "/var/log"
-mount -t tmpfs none "/var/lib/docker"
-mount -t proc none "/proc"
-mkdir "/dev/pts"
-mount -t devpts none "/dev/pts"
-mkdir "/dev/shm"
-mknod -m 444 /dev/urandom c 1 9
-mount -t tmpfs none "/dev/shm"
-mount -t sysfs none "/sys"
-mount -t tmpfs none "/sys/fs/cgroup"
 
-DOCKER_STORAGE="/var/lib/docker"
-mkdir -p /var/lib/docker
-mount none /var/lib/docker -t hostfs -o $DOCKER_STORAGE
-# mount -t tmpfs -o size=8g tmpfs "/var/lib/docker"
-
-for SUBSYS in memory devices cpuset cpu; do
-	mkdir "/sys/fs/cgroup/$SUBSYS"
-	mount -t cgroup -o "$SUBSYS" none "/sys/fs/cgroup/$SUBSYS"
-done
-echo 1 > "/proc/sys/net/ipv4/ip_forward"
-echo 0 > "/proc/sys/kernel/printk"
-ip addr add 127.0.0.1 dev lo
-ip link set lo up
-ip addr add 10.1.1.1/24 dev eth0
-ip link set eth0 up
-ip route add default via 10.1.1.254
-
-# This is to handle when /etc/resolv.conf -> /run/resolvconf/resolv.conf
-[ -L "/etc/resolv.conf" ] && {
-	mkdir -p "$(dirname "$(readlink --canonicalize-missing /etc/resolv.conf)")"
-	[ -f "/etc/resolv.conf" ] || {
-		cat "/var/log/resolv.conf" > "/etc/resolv.conf"
+REQUIREMENTS="/sbin/ip /usr/bin/slirp-fullbolt"
+for R in $REQUIREMENTS
+do
+	[ -x $R ] || {
+		echo "Requirement $R not found. Aborting."
+		exit 1
 	}
-}
+done
 
-[ -f "/var/log/output" ] && {
-	exec >>"/var/log/output"
-	exec 2>>"/var/log/output"
-}
-sh "/var/log/cmd"
-echo $? >/var/log/status
-# This will make sure that the main "tail" process had the opportunity
-# to display everything before being killed by UML misbehavior.
-sleep 1
+if [ "$2" ]
+then
+	shift
+	echo "Extraneous arguments: $*"
+	echo "Try to enclose them within quotes?"
+	exit 255
+fi
+
+if [ -n "$SLIRP_PORTS" ] && [ -z "$HOST_IP" ]
+then
+    echo "The HOST_IP must be defined to setup redirects with SLIRP_PORTS."
+    exit 255
+fi
+
+LOGDIR=/tmp/log.$$
+mkdir $LOGDIR
+
+if [ "$1" ] 
+then
+	CMD="$1"
+	STDIN=/dev/null
+	STDOUT=/dev/null
+	STDERR=/dev/null
+	touch $LOGDIR/output
+	if [ "$VERBOSE" = 1 ]; then
+		tail -f $LOGDIR/output &
+	fi
+	TAILPID=$!
+	trap '' TERM
+else
+	CMD=/bin/bash
+	STDIN=/dev/stdin
+	STDOUT=/dev/stdout
+	STDERR=/dev/stderr
+	TAILPID=""
+fi
+
+cat /etc/resolv.conf > $LOGDIR/resolv.conf
+
+echo "$CMD" > $LOGDIR/cmd
+INITDIR="$(readlink --canonicalize $(dirname "$0"))"
+$INITDIR/uml quiet mem=3G rootfstype=hostfs rootflags=/ ro \
+	eth0=slirp,,$INITDIR/slirp-wrapper \
+	init=$INITDIR/init LOGDIR="$LOGDIR" \
+	<$STDIN >$STDOUT 2>$STDERR
+
+# Due to a weird behavior of usermodelinux, sometimes it will kill the
+# whole process group, and we won't have to kill tail. Duh.
+[ "$TAILPID" ] && [ -d /proc/$TAILPID ] && 
+	/bin/kill $TAILPID >/dev/null 2>/dev/null
+
+STATUS=""
+[ -f "$LOGDIR/status" ] && STATUS="$(cat $LOGDIR/status)"
+[ "$DEBUG" ] || rm -rf "$LOGDIR"
+[ "$STATUS" ] && exit $STATUS
+exit 255
